//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mySurvey.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ReplyB
    {
        public int ReplyBID { get; set; }
        [Required(ErrorMessage = "Vælg et svar")]
        public Nullable<bool> ReplyB_1 { get; set; }
        [Required(ErrorMessage = "Vælg et svar")]
        public Nullable<bool> ReplyB_2 { get; set; }
        [Required(ErrorMessage = "Vælg et svar")]
        public Nullable<bool> ReplyB_3 { get; set; }
        [Required(ErrorMessage = "Vælg et svar")]
        public Nullable<bool> ReplyB_4 { get; set; }
        [Required(ErrorMessage = "Vælg et svar")]
        public Nullable<bool> ReplyB_5 { get; set; }
        [Required(ErrorMessage = "Vælg et svar")]
        public Nullable<bool> ReplyB_6 { get; set; }
        [Required(ErrorMessage = "Vælg et svar")]
        public Nullable<bool> ReplyB_7 { get; set; }
        [Required(ErrorMessage = "Vælg et svar")]
        public Nullable<bool> ReplyB_8 { get; set; }
        [Required(ErrorMessage = "Vælg et svar")]
        public Nullable<bool> ReplyB_9 { get; set; }
        [Required(ErrorMessage = "Vælg et svar")]
        public Nullable<bool> ReplyB_10 { get; set; }
    }
}
